# DOCKER BUILD & RUN
services:
  db:
    image: mysql:8.0
    container_name: bankapp_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin","ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ai-bankapp

  bankapp:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      OLLAMA_URL: ${OLLAMA_URL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ai-bankapp

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai-bankapp

# DOCKER VOLUME CREATE
volumes:
  mysql_data:
  ollama_data:

# DOCKER NETWORK CREATE
networks:
  ai-bankapp:
    driver: bridge
