apiVersion: v1
kind: Secret
metadata:
  name: bankapp-secrets
  namespace: bankapp-ns
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: CHANGE_ME
  MYSQL_PASSWORD: CHANGE_ME

# Placeholder values only, root credentials should be injected during deployment
